### ISSUE TITLE
Unable to handle high precision floating point values.

### ISSUE THREAD

**Issue by sarthakjain95** [SwarajayaOjha/Siborg#2]
I was just sitting on my bed, looking at this glorious code when I noticed that it can't really handle more than 7 digits of floating-point precision. It'd be really awesome if you can just change that 'float' to a 'double' so that we can live a better life.
```c 
double num1,num2,result=0;
```

**Comment by aadhav-n1** [comment]
@SwarajayaOjha This might be a viable solution. Changing to `double` from `float` helps in allowing more precision. I hope you would implement this in the future.

**Comment by SwarajayaOjha** [comment]
@sarthakjain95 While you were sitting on your bed and were having a look at this code you might also have read the title which says basic calculator. I think 7 points of decimal for a basic calculator is pretty good. But never mind I respect your suggestion and will try to look after it from now.
One suggestion to you from my side is that if you really need a highly precised output kindly try using a scientific calculator.

**Comment by sarthakjain95** [comment]
Jeez. You could've just changed that one line. It was just a suggestion. No need to be a dick.

**Comment by SwarajayaOjha** [comment]
actually you are trying to be a dick. moreover dick of a roadside pervert . just trying to insert it in every hole possible. sometimes even at such places where it should not be inserted or there is no need of inserting that useless DICK...
